# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5968def7377e169c15d30f374ddecd36647d7220b788f9a6911d146f6e67d9d8462f575b79b7854c170fb7abdc194ff943d2d0c6b62f03ce3d1589cc41a53748

test:
  secret_key_base: 7d7cd3bcb9531886b04b34f1910fbfd56e4dfff349ad14ffa9115559a187360693c2b92cf232b3c75d1f50fb46e8e9b6aee6ff71c4188ce0dc754fa76f82d496

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
